version: "3.9"

services:
  app:
    restart: unless-stopped
    container_name: airbnb-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

  postgres:
    restart: unless-stopped
    container_name: postgres-db
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: airBnb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: